#!/bin/bash

if [[ $(id -u) -ne 0 ]]; then
    echo "Not running as root."
    exit
fi
echo "Setting up Dean's nice defaults"

# Install packages as root first.
for program in vim git tmux python3-pip python3-venv gdebi gcc sqlite3 curl
do
    sudo apt-get --assume-yes install $program > /dev/null
done

# SSH
echo "Setting up SSH configuration"
rm /home/dean/.ssh/config > /dev/null
su -c "ln -s setup/ssh_config /home/dean/.ssh/config" dean > /dev/null

if test -f "/home/dean/.ssh/id_rsa.pub"; then
    echo "Generating a new SSH Key"
    #su -c ssh-keygen dean
    echo "Add this SSH key to git accounts"
    cat /home/dean/.ssh/id_rsa.pub
fi

# Vim
rm /home/dean/.vimrc > /dev/null
su -c "ln -s /home/dean/setup/vimrc /home/dean/.vimrc" dean > /dev/null

# Bash
rm /home/dean/.bashrc > /dev/null
su -c "ln -s /home/dean/setup/bashrc /home/dean/.bashrc" dean > /dev/null

# Git
echo "Setting email and name for git config"
su -c "git config --global user.email \"deanwunder@gmail.com\"" dean
su -c "git config --global user.name \"Dean Wunder\"" dean

# Custom binaries
echo "Setting up custom home directory binaries"
su -c "ln -s /home/dean/setup/bin /home/dean/bin" dean


